name: geolocalizer
channels:
  - bioconda
  - defaults
dependencies:
  - attrs=19.3.0=py_0
  - biopython=1.77=py38haf1e3a3_0
  - blas=1.0=mkl
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py38_0
  - clustalo=1.2.3=0
  - intel-openmp=2019.4=233
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=haf1e3a3_0
  - libffi=3.3=h0a44026_1
  - libgfortran=3.0.1=h93005f0_2
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38hfbe908c_0
  - mkl_fft=1.1.0=py38hc64f4ea_0
  - mkl_random=1.1.1=py38h959d312_0
  - more-itertools=8.4.0=py_0
  - ncurses=6.2=h0a44026_1
  - numpy=1.18.5=py38h1da2735_0
  - numpy-base=1.18.5=py38h3304bdc_0
  - openssl=1.1.1g=h1de35cc_0
  - packaging=20.4=py_0
  - pip=20.1.1=py38_1
  - pluggy=0.13.1=py38_0
  - py=1.9.0=py_0
  - pyparsing=2.4.7=py_0
  - pytest=5.4.3=py38_0
  - python=3.8.3=h26836e1_2
  - readline=8.0=h1de35cc_0
  - setuptools=47.3.1=py38_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - wcwidth=0.2.5=py_0
  - wheel=0.34.2=py38_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/romeer/anaconda3/envs/geolocalizer

